version: '3'
services:
  my-postgres:
    image: postgres
    ports:
      - "8888:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./Project2.sql:/docker-entrypoint-initdb.d/create_tables.sql
    oom_kill_disable: true
    privileged: true
  javalin-backend-service:
    image: javalin-backend
    build: .
    ports:
      - 9999:4040
    depends_on:
      - my-postgres
      - project_2_backend-my-postgres-1
    links:
      - my-postgres


